function [u1,u2,u3] = adaptive_quadrature_wrapper(curve,density,targets,opts)
%ADAPTIVE_QUADRATURE_WRAPPER  Wrapper for adaptive quadrature
%
%   [u1,u2,u3] = adaptive_quadrature_wrapper(curve,density,targets,opts)

    [tj_ref, wj_ref, ~] = adaptive_panelization(curve.s, opts.nquad, opts.tol);

    [u1,u2,u3] = adaptive_quadrature( ...
        curve.x(tj_ref), curve.y(tj_ref), curve.z(tj_ref), ...
        curve.s(tj_ref), wj_ref, ...
        density.f1(tj_ref), density.f2(tj_ref), density.f3(tj_ref), ...
        targets(1,:), targets(2,:), targets(3,:), ...
        opts.nquad, opts.slender_eps, opts.Hlim);
end
